### PR TITLE
Fix #166: Audit does not work when auto-commit disabled

### LINKED ISSUE #166: Audit does not work when auto-commit disabled
Audit does not work when auto-commit disabled because of `DatabaseAuditWriter` misuse of transaction configuration. Not transaction public methods are calling methods of the same bean, but it does not go through transaction proxy. So inserts are not committed.

See Spring explanation https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop-understanding-aop-proxies

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java [hunk 1]
```diff
@@ -141,117 +148,126 @@ public void write(AuditRecord auditRecord) {
...
-            while (!queue.isEmpty()) {
-                try {
-                    final List<AuditRecord> auditsToPersist = new ArrayList<>(batchSize);
-                    final List<AuditParam> paramsToPersist = new ArrayList<>();
-                    for (int i = 0; i < batchSize; i++) {
-                        AuditRecord record = queue.take();
-                        auditsToPersist.add(record);
-                        for (Map.Entry<String, Object> entry : record.getParam().entrySet()) {
-                            paramsToPersist.add(new AuditParam(record.getId(), record.getTimestamp(), entry.getKey(), entry.getValue()));
+            transactionTemplate.executeWithoutResult(status -> {
```
Comment (banterCZ) [inline audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:162]: 👀 This is the key change. I recommend to review it with hidden whitespace.

**Review by romanstrobl — APPROVED** [review]
Nice discovery, thanks for fixing this issue!
