### PR TITLE
Fix #301: Change transaction propagation of DatabaseAuditWriter#flush to REQUIRES_NEW

### LINKED ISSUE #301: Change transaction propagation of DatabaseAuditWriter#flush to REQUIRES_NEW
Default transaction propagation is `PROPAGATION_REQUIRED`. But when `DatabaseAuditWriter#write` is executed from the service method annotated by `@Transactional(readOnly = true)` and `remainingCapacity` of the audit record queue is exhausted, the `#flush` would fail.

It is a very rare possibility but it has to be fixed.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java [hunk 1]
```diff
@@ -159,6 +160,7 @@ public void flush() {
         }
 
         synchronized (FLUSH_LOCK) {
+            transactionTemplate.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
```
Comment (banterCZ) [inline audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:163]: I have really tried to create a test, but the H2 engine does not respect the read-only option to simulate that.
