### PR TITLE
Fix #176: Redesign RestClientConfiguration

### LINKED ISSUE #176: Redesign RestClientConfiguration
Redesign `RestClientConfiguration`. It is abused as `@ConfigurationProperties`, but it contains also beans such as `ObjectMapper` which cause an issue https://github.com/wultra/enrollment-server/issues/722 since Spring Boot 3. There could be a similar problem with ExchangeFilterFunction.

```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'enrollment-server.user-info.rest-provider.rest-client-config.object-mapper.serializer-provider.generator.write-capabilities' to com.fasterxml.jackson.core.util.JacksonFeatureSet<com.fasterxml.jackson.core.StreamWriteCapability>
```

Find out a way how to pass simple configuration properties and other beans to the `RestClient`.

Consider passing `JacksonProperties` as mentioned at https://github.com/spring-projects/spring-boot/issues/35091#issuecomment-1516051146

Object mapper is configured in TPP Engine Client https://github.com/wultra/powerauth-webflow/blob/develop/powerauth-tpp-engine-client/src/main/java/io/getlime/security/powerauth/lib/tpp/engine/client/TppEngineClient.java#L77

Introduced in https://github.com/wultra/lime-java-core/pull/29/files

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: rest-client-base/src/main/java/com/wultra/core/rest/client/base/RestClientConfiguration.java [hunk 1]
```diff
@@ -15,17 +15,23 @@
...
 import org.springframework.web.reactive.function.client.ExchangeFilterFunction;
 
 import java.time.Duration;
 import java.util.Arrays;
+import java.util.EnumMap;
+import java.util.Map;
 
 /**
  * REST client configuration.
+ * This class is safe to use as {@code org.springframework.boot.context.properties.ConfigurationProperties}.
```
Comment (banterCZ) [inline rest-client-base/src/main/java/com/wultra/core/rest/client/base/RestClientConfiguration.java:34]: `ObjecMapper` configuration example: `enrollment-server.user-info.rest-provider.restClientConfig.jacksonConfiguration.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true`

**Review by romanstrobl — APPROVED** [review]
Nice solution!
