### PR TITLE
Fix #34: Auditing for PowerAuth backends

### LINKED ISSUE #34: Auditing for PowerAuth backends
Implement a solution for auditing in PowerAuth backends with following requirements.

1. Use the following fields for auditing:
  - timestamp
  - application
  - event type (informational, exception)
  - message (free text with logged message)
  - level of severity
  - user ID (optional)
  - operation ID (operation from audited component, optional)
  - external operation ID (operation from parent component, optional)
  - activation ID (only when PowerAuth is used, optional)
  - extras (additional details, optional)
  - stack trace (for exception, optional)

2. The auditing code should be reusable across multiple PowerAuth projects and it should be available as an optional dependency.

3. The auditing table name needs to be configurable to allow auditing from multiple projects into the same table.

4. Supported databases:
- MySQL
- Oracle
- PostgreSQL

5. Use spring properties for configuration of the library with reasonable defaults (e.g. auditing table name).

### PR DESCRIPTION
**Pull request by romanstrobl**
A minimalistic implementation of backend DB auditing is ready. I still need to work on JavaDoc and documentation.  

Check the tests for sample usage for now, just note that the `flush` method will not be called in actual code, this is only used for testing.

### CODE REVIEW

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAudit.java [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+    @Override
+    public void error(String message, Map<String, Object> param, Object... args) {
+        errorInternal(message, param, args);
+    }
+
+    private void errorInternal(String message, Map<String, Object> param, Object[] args) {
+        if (!isErrorEnabled()) {
+            return;
+        }
+        AuditRecord auditRecord = new AuditRecord(message, AuditLevel.ERROR, param, args);
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAudit.java]: Use `final`, let's be fancy! ;-)

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java [hunk 2]
```diff
@@ -0,0 +1,244 @@
...
+ * Database audit writer.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+@Service
+public class DatabaseAuditWriter implements AuditWriter {
+
+    private static final Logger logger = LoggerFactory.getLogger(DatabaseAuditWriter.class);
+
+    private static final String SQL_INSERT_INTO = "INSERT INTO ";
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:53]: I am not sure about this. Does it make the code more readable?

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java [hunk 3]
```diff
@@ -0,0 +1,244 @@
...
+        synchronized (CLEANUP_LOCK) {
+            jdbcTemplate.execute( SQL_DELETE_FROM + tableName + SQL_CLEANUP_CONDITION, (PreparedStatementCallback<Boolean>) ps -> {
+                ps.setTimestamp(1, Timestamp.valueOf(cleanupLimit));
+                return ps.execute();
+            });
+            logger.debug("Audit records older than {} were deleted", cleanupLimit);
+        }
+    }
+
+    @Scheduled(fixedDelayString = "${audit.flush.delay.fixed:1000}", initialDelayString = "${powerauth.audit.flush.delay.initial:1000}")
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:227]: This will cause issues when running in multiple instances. I suggest either:

- Removing scheduled cleanup from the library and delegating this to the application (including documentation).
- Implementing some multi-node locking (Shedlock with JDBC).

File: audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+import java.util.Objects;
+
+/**
+ * Audit record model class.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+public class AuditRecord {
+
+    private final Date timestamp;
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java:33]: I am missing some:

- Correlation ID to be able to group records from the same process.
- Event type to simplify queries.

File: audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+    private final AuditLevel level;
+    private final Map<String, Object> param;
+    private String message;
+    private Throwable throwable;
+    private Class<?> callingClass;
+    private String threadName;
+
+    public AuditRecord(String message, AuditLevel level, Map<String, Object> param, Object[] args) {
+        if (message == null) {
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java:42]: Can we use annotations for this?

File: audit-base/src/main/java/com/wultra/core/audit/base/util/JsonUtil.java [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+/**
+ * JSON serialization utilities.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+public class JsonUtil {
+
+    private static final Logger logger = LoggerFactory.getLogger(JsonUtil.class);
+
+    private final ObjectMapper objectMapper = new ObjectMapper();
```
Comment (petrdvorak) [inline audit-base/src/main/java/com/wultra/core/audit/base/util/JsonUtil.java:34]: This could maybe use a bit more fine-grained initialization in the constructor, i.e., to enforce the right date format, avoid serializing null value, etc.

**Review by petrdvorak — APPROVED** [review]
Generally, it looks good. I have several comments we can have a look at, especially regarding the audit log item.

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java (hunk 2 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:53]: Added.

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java (hunk 3 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:234]: There is no issue with created audit records, each instance creates is own records, so no locking is required. 

During cleanup the issue is also not as significant as it seems, because:
- multiple `DELETE` queries can run in parallel, no locking is required, the DB can handle this easily
- the `DELETE` queries are by default executed once per hour by default (this value can be customized) and are very likely to be executed in different times by different nodes
- an index is created on the `created_timestamp` column, so the `DELETE` queries should be fast

We can add a locking solution, but I think it is an overkill for this use case.

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAudit.java (hunk 1 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAudit.java]: Added.

File: audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java (hunk 5 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java:42]: Yes, I will add the validations.

File: audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java (hunk 4 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java:33]: I suggest we use the generic `param` map for this use case. As discussed, I will move these auditing parameters into a separate database table. The queries can be done on SQL level, e.g. `SELECT * FROM audit_log al INNER JOIN audit_param ap ON al.audit_log_id=ap.audit_log_id WHERE key = "correlation_id" and value = "..." `. Otherwise we would have to add new parameters into the `Audit` interface which would expand the interface quite a lot.

**Comment by romanstrobl** [comment]
As discussed, we will use a separate database table for auditing parameters instead of using dynamic columns. This change will have a minor impact on performance (slower inserts, deletes and queries) and on usability (admin will need to execute a join query). However the change will guarantee the database structure is not different per project.

File: audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java (hunk 2 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/database/DatabaseAuditWriter.java:53]: Ok, we can change it back.

**Comment by romanstrobl** [comment]
The pull request is now ready for review. If any functionality is still missing, let's raise these changes as separate tickets, I am sure there are many ways how we can nicely extend the feature set, but I try to keep the number of features minimal for the first release.

**Comment by romanstrobl** [comment]
As for the categorization, we could replace `Map<String, Object> param` by a builder, e.g.:
```
audit.warn("access denied", 
   AuditDetail.type(AuditTypes.SECURITY)
      .addParam("operation_id", operationId)
      .addParam("user_id", userId)
      .build(),
   ex);
```

Where `AuditTypes.SECURITY` is a String constant defined in the project which uses this library. The `type` would be logged into the main `audit_log` table, the parameters would be logged into the `audit_param` table.

File: audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java (hunk 4 above)
Comment (romanstrobl) [reply audit-base/src/main/java/com/wultra/core/audit/base/model/AuditRecord.java:35]: Added in a separate pull request into this branch so that we can easily see the impact of these changes: https://github.com/wultra/lime-java-core/pull/48

**Review by petrdvorak — APPROVED** [review]
Looks OK
